<a href="https://colab.research.google.com/github/Sarvesh-joshi273/sarvesh/blob/main/task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Data type:", arr2.dtype)


1D Array:
[10 20 30 40 50]
Shape: (5,)
Data type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data type: int64


In [ ]:


arr1 = np.zeros(8)

arr2 = np.ones((4, 4))

arr3 = np.zeros((3, 3))

print("1D Array of 8 zeros:")
print(arr1)

print("\n2D Array (4x4) of ones:")
print(arr2)

print("\n3x3 Matrix of zeros:")
print(arr3)


1D Array of 8 zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

2D Array (4x4) of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:


arr1 = np.arange(0, 21, 1)

arr2 = np.arange(10, 51, 2)

arr3 = np.arange(5, 101, 5)

print("a) Numbers from 0 to 20:")
print(arr1)

print("\nb) Even numbers from 10 to 50:")
print(arr2)

print("\nc) Numbers from 5 to 100 (step 5):")
print(arr3)


a) Numbers from 0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

b) Even numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

c) Numbers from 5 to 100 (step 5):
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:


arr1 = np.linspace(0, 5, 10)

arr2 = np.linspace(10, 10, 15)

print("a) 10 equally spaced numbers between 0 and 5:")
print(arr1)
print("Length:", len(arr1))

print("\nb) 15 equally spaced numbers between 10 and 10:")
print(arr2)
print("Length:", len(arr2))


a) 10 equally spaced numbers between 0 and 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

b) 15 equally spaced numbers between 10 and 10:
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
Length: 15


In [ ]:

arr1 = np.random.rand(10)

arr2 = np.random.randn(3, 3)

arr3 = np.random.randint(10, 51, size=(4, 5))

print("a) 1D Array of 10 random numbers between 0 and 1:")
print(arr1)

print("\nb) 3x3 Matrix of random numbers (standard normal distribution):")
print(arr2)

print("\nc) 2D Array (4x5) of random integers between 10 and 50:")
print(arr3)


a) 1D Array of 10 random numbers between 0 and 1:
[0.18302321 0.32435049 0.68637985 0.2361036  0.29775158 0.63699984
 0.93771294 0.31990134 0.84227218 0.19225117]

b) 3x3 Matrix of random numbers (standard normal distribution):
[[ 1.02888585 -1.4676078  -0.08456683]
 [ 0.3911744   1.4579615  -0.76397454]
 [-0.74125044  0.11237762 -0.1071032 ]]

c) 2D Array (4x5) of random integers between 10 and 50:
[[19 25 22 37 14]
 [31 21 50 45 25]
 [18 47 26 43 44]
 [14 11 25 28 31]]


In [ ]:

v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

add = v1 + v2

sub = v1 - v2

mul = v1 * v2

dot = np.dot(v1, v2)

print("v1:", v1)
print("v2:", v2)

print("\nAddition:", add)
print("Subtraction:", sub)
print("Element-wise Multiplication:", mul)
print("Dot Product:", dot)


v1: [2 4 6 8]
v2: [1 3 5 7]

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56]
Dot Product: 100


In [ ]:


# Create matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

add = A + B

matmul = A @ B

elem_mul = A * B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition (A + B):")
print(add)

print("\nMatrix Multiplication (A @ B):")
print(matmul)

print("\nElement-wise Multiplication (A * B):")
print(elem_mul)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:

arr = np.random.randint(1, 101, size=(4, 4))

print("4x4 Matrix of random integers:")
print(arr)

print("\nShape:", arr.shape)
print("Dimension (ndim):", arr.ndim)
print("Total number of elements (size):", arr.size)
print("Data type:", arr.dtype)


4x4 Matrix of random integers:
[[94 94 55 21]
 [28 18 53 93]
 [93  8 68 30]
 [76 51 22 87]]

Shape: (4, 4)
Dimension (ndim): 2
Total number of elements (size): 16
Data type: int64


In [ ]:

arr = np.random.randint(1, 51, size=20)

matrix = arr.reshape(4, 5)

print("4x5 Matrix:")
print(matrix)

print("\nSum of all elements:", matrix.sum())
print("Mean of all elements:", matrix.mean())
print("Standard Deviation:", matrix.std())

print("\nMaximum value in each row:")
print(matrix.max(axis=1))


4x5 Matrix:
[[20 27 44 33 15]
 [28 16 29 35 46]
 [35 10 49 27 35]
 [20 18 24 42 10]]

Sum of all elements: 563
Mean of all elements: 28.15
Standard Deviation: 11.394187114489563

Maximum value in each row:
[44 46 49 42]


In [ ]:
try:
    n = int(input("Enter how many numbers to generate: "))

    arr = np.random.randint(10, 101, size=n)

    print("\nGenerated Array:")
    print(arr)

    print("\nMean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))

    if n % 2 == 0:
        matrix = arr.reshape(2, n // 2)
        print("\nReshaped 2D Array:")
        print(matrix)

        print("\nRow-wise Sum:")
        print(matrix.sum(axis=1))
    else:
        print("\nCannot reshape into 2D array (number not divisible by 2).")

except:
    print("Please enter a valid integer!")


Enter how many numbers to generate: 3

Generated Array:
[15 46 38]

Mean: 33.0
Median: 38.0
Standard Deviation: 13.140268896284683
Minimum: 15
Maximum: 46

Cannot reshape into 2D array (number not divisible by 2).
