<a href="https://colab.research.google.com/github/Sarvesh-joshi273/sarvesh/blob/main/task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.random.randint(10, 101, size=(5, 6))

print("Array:\n", arr)

print("Shape of the array:", arr.shape)
print("Total number of elements (size):", arr.size)
print("Data type (dtype):", arr.dtype)


Array:
 [[38 78 62 71 39 74]
 [84 57 97 18 88 27]
 [42 22 69 98 56 52]
 [92 71 13 34 38 36]
 [48 87 76 50 73 50]]
Shape of the array: (5, 6)
Total number of elements (size): 30
Data type (dtype): int64


In [ ]:
arr = np.random.randint(1, 51, size=20)

print("Array:", arr)
print("Minimum value:", arr.min())
print("Index of minimum value:", arr.argmin())
print("Maximum value:", arr.max())
print("Index of maximum value:", arr.argmax())
print("Sum of elements:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())


Array: [48 42 14 36 38 15 21 23 30 48 21 21 25 18 16  4  7 21 50 36]
Minimum value: 4
Index of minimum value: 15
Maximum value: 50
Index of maximum value: 18
Sum of elements: 534
Mean: 26.7
Standard Deviation: 13.293231360357796


In [ ]:
arr = np.random.randint(20, 81, size=(4, 5))

print("Matrix:\n", arr)

print("Minimum value:", arr.min())
print("Maximum value:", arr.max())
print("Sum of all elements:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

print("Sum of each row:", arr.sum(axis=1))
print("Sum of each column:", arr.sum(axis=0))


Matrix:
 [[40 24 31 43 53]
 [70 77 72 34 78]
 [21 57 78 20 42]
 [77 64 24 33 47]]
Minimum value: 20
Maximum value: 78
Sum of all elements: 985
Mean: 49.25
Standard Deviation: 20.461854754640402
Sum of each row: [191 331 218 245]
Sum of each column: [208 222 205 130 220]


In [ ]:
arr = np.arange(1, 25)

arr1 = arr.reshape(4, 6)
arr2 = arr.reshape(3, 8)
arr3 = arr.reshape(2, 3, 4)

print("Original 1D array:", arr)
print("Reshaped to 4x6:\n", arr1)
print("Shape:", arr1.shape)

print("Reshaped to 3x8:\n", arr2)
print("Shape:", arr2.shape)

print("Reshaped to 2x3x4 (3D array):\n", arr3)
print("Shape:", arr3.shape)


Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshaped to 4x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
Reshaped to 3x8:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)
Reshaped to 2x3x4 (3D array):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Array:\n", arr)

print("First row:", arr[0])

print("Last column:", arr[:, -1])

print("Center 2x2 submatrix:\n", arr[1:3, 1:3])

print("All even numbers:", arr[arr % 2 == 0])


Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First row: [10 20 30 40]
Last column: [ 40  80 120]
Center 2x2 submatrix:
 [[ 60  70]
 [100 110]]
All even numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:
arr = np.random.randint(1, 101, size=(5, 5))

print("Original Matrix:\n", arr)

print("Diagonal elements:", np.diag(arr))

print("Elements greater than 50:", arr[arr > 50])

arr[arr < 30] = 0

print("Modified Matrix:\n", arr)


Original Matrix:
 [[17 97 23 10 17]
 [12 83  7 11 51]
 [69 79 20 75  4]
 [76 21 16 10  1]
 [87 77 65  3 64]]
Diagonal elements: [17 83 20 10 64]
Elements greater than 50: [97 83 51 69 79 75 76 87 77 65 64]
Modified Matrix:
 [[ 0 97  0  0  0]
 [ 0 83  0  0 51]
 [69 79  0 75  0]
 [76  0  0  0  0]
 [87 77 65  0 64]]


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Element-wise power:", a ** b)
print("Modulo operation:", a % b)


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Element-wise power: [     10     400   27000 2560000]
Modulo operation: [0 0 0 0]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("Element-wise multiplication:\n", A * B)

print("Matrix multiplication:\n", A @ B)



Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
arr = np.random.randn(6, 6)

print("Original Matrix:\n", arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

print("Index of maximum value:", arr.argmax())
print("Index of minimum value:", arr.argmin())

print("Top-left 3x3 submatrix:\n", arr[:3, :3])

arr = np.abs(arr)

print("Modified Matrix:\n", arr)

print("Mean of modified matrix:", arr.mean())


Original Matrix:
 [[-1.00171571 -1.32032127  2.17224986  0.5780732  -1.08394852  0.46730274]
 [ 0.64646396  0.15239424 -0.21851209  1.59010276 -0.72742065 -1.9097283 ]
 [ 1.14327286 -0.71984931 -1.87505316 -0.26715273 -0.98808148 -1.88099053]
 [ 1.3529468  -0.34875744  0.24187233  0.42134974 -0.30290356 -0.06658975]
 [ 0.49756059  1.12544104 -0.63714897 -0.18927124  0.83809656  0.24827178]
 [-0.39792939 -0.03363368  0.06186302 -0.77118238  1.0348721   1.8940304 ]]
Shape: (6, 6)
Size: 36
Data type: float64
Index of maximum value: 2
Index of minimum value: 11
Top-left 3x3 submatrix:
 [[-1.00171571 -1.32032127  2.17224986]
 [ 0.64646396  0.15239424 -0.21851209]
 [ 1.14327286 -0.71984931 -1.87505316]]
Modified Matrix:
 [[1.00171571 1.32032127 2.17224986 0.5780732  1.08394852 0.46730274]
 [0.64646396 0.15239424 0.21851209 1.59010276 0.72742065 1.9097283 ]
 [1.14327286 0.71984931 1.87505316 0.26715273 0.98808148 1.88099053]
 [1.3529468  0.34875744 0.24187233 0.42134974 0.30290356 0.06658975]

In [ ]:
marks = np.random.randint(30, 101, size=(10, 5))

print("Student Marks (10x5):\n", marks)

total_marks = marks.sum(axis=1)
average_marks = marks.mean(axis=1)

print("Total marks of each student:", total_marks)
print("Average marks of each student:", average_marks)

print("Student with highest total marks (index):", total_marks.argmax())
print("Student with lowest total marks (index):", total_marks.argmin())

print("Class mean:", marks.mean())
print("Class standard deviation:", marks.std())

top3_indices = total_marks.argsort()[-3:][::-1]
print("Marks of top 3 students:\n", marks[top3_indices])


Student Marks (10x5):
 [[86 37 46 54 43]
 [38 46 54 86 82]
 [40 68 74 87 51]
 [52 45 68 67 86]
 [58 55 38 84 88]
 [37 46 79 52 99]
 [59 51 68 54 35]
 [91 54 31 80 77]
 [67 41 43 70 79]
 [94 87 62 86 53]]
Total marks of each student: [266 306 320 318 323 313 267 333 300 382]
Average marks of each student: [53.2 61.2 64.  63.6 64.6 62.6 53.4 66.6 60.  76.4]
Student with highest total marks (index): 9
Student with lowest total marks (index): 0
Class mean: 62.56
Class standard deviation: 18.69455535710866
Marks of top 3 students:
 [[94 87 62 86 53]
 [91 54 31 80 77]
 [58 55 38 84 88]]
